server.port=${PORT:8082}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5434/estoque}
spring.datasource.username=${DATABASE_USERNAME:estoque}
spring.datasource.password=${DATABASE_PASSWORD:estoque123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false